from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    def store(self, key: str, data: bytes) -> str: ...

    def retrieve(self, key: str) -> bytes: ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> None: ...

    def get_url(self, key: str, expires_in: int = 3600) -> str: ...
